name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
#     - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'UMN-LATIS'
        reponame: 'dendro-plots'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
